### ISSUE TITLE
인프라 구축에서 난항을 겪고 있습니다.

### ISSUE THREAD

**Issue by BOOOO0** [2023-Ak/Ak#1]
정확하게는 구축 이후 세부적인 부분에서 난항을 겪고 있습니다.

네이버 클라우드 플랫폼 깃허브에서 Terraform으로 VPC 환경의 서버를 구성하는 시나리오 코드를 제공하기 때문에 

그것을 참고하고 리소스 생성은 원활했습니다.

당초 단계적으로 설계했던 아키텍처를 네이버 클라우드를 사용해서 설계했던 아키텍처 중 최종 부분을 구축하려고 했으나 

public server -> private server로의 통신에서 난항을 겪고 있습니다.

SSH키를 사용한 접속을 시도하고 ACL 룰을 바꿔보고 Ansible로 ping을 보내는 등 여러 시도를 했으나 통신이 되지 않았습니다.

네이버 클라우드는 VPC 환경으로 구축할 경우 ACG가 아닌 ACL을 반드시 사용해야 하는데

인바운드 룰과 아웃바운드 룰의 설정을 예시 코드를 통해 설정했고 잘 적용되어 있으나 통신이 되지 않고 있습니다.

private server로의 통신이 원활하지 않으므로 public server로 모두 구성하는 방법이 있으나

우선은 최종 아키텍처를 최종 목표로 하는 것은 그대로 유지할 생각입니다.

AWS를 사용해서 ACG를 사용한 포트 포워딩을 하는 것도 가능해 보이나 지금 문제가 ACL의 문제인지 정확하지 않고

public subnet을 그대로 유지할 경우 NAT Gateway의 사용이 필요한데 이 부분은 리소스 생성과 동시에 

비용이 발생하기 때문에 사용할 수 없습니다.

물론 대안은 있습니다.

AWS를 사용해서 public subnet에 클라이언트 서버와 데이터베이스를 포함한 서버를 구성하는 경우 

클라이언트 측 CI/CD와 서버 내 세부적인 부분 설정은 이미 결과물이 있기 때문에 별도의 과정 거의 없이 그대로 적용이 가능하고

서버 측 CI/CD와 양 서버 간 통신만 확인하면 그대로 출시도 가능합니다.

그리고 네이버 클라우드도 VPC 환경이 아닌 클래식 서버를 사용하거나 public server로 구성할 경우 가능할 것으로 보입니다.

하지만 public server에 Nginx 서버를 설치한 후 IP를 사용해서 접속했으나 접속이 되지 않고 기본 DNS를 제공하지 않아

IP를 통한 접속만 가능한 등 여전히 애로사항이 존재합니다.

당초 계획대로 아키텍처 자체는 클라이언트와 데이터베이스를 포함한 서버 두 개의 서버로 구성을 우선으로 하고

어떤 플랫폼을 사용할 지는  크레딧이 있기 때문에 확장 시 자유도가 높은 네이버 클라우드를 우선으로 하며

시간을 충분히 사용한 이후에도 구축이 원활하지 않을 경우 AWS를 사용하는 것으로 하겠습니다.

그렇게 된다면 배포에 긴 시간이 걸리지 않을 것입니다.

**Comment by YukDDong** [comment]
모든 부분을 이해하진 못했지만 네이버 클라우드를 통해서 ( 클라이언트 서버1개 DB+백엔드 서버 1개 )로 진행하는데 구축이 원할하지 않을경우 AWS로 전환한다는 걸로 이해하면 될까요??

**Comment by BOOOO0** [comment]
ACL 룰을 재설정해서 현재 public server -> private server로 통신이 가능해졌습니다.
그런데 public server에 Nginx를 설치하고 배포중인데 IP를 통해 접속해도 계속 응답이 없습니다.
이전엔 단순히 설치 후 실행만 해도 바로 확인이 가능했는데 안되는 걸 보니 이 부분도 아마 ACL 룰 문제인 듯 합니다.
만약 이 부분이 해결된다면 당장 배포에는 큰 문제가 없을 듯 합니다.
